{
 "title": "My Other Dashboard",
 "tags": [
  "one",
  "two",
  "three"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(memcached_up, cluster)"
   },
   {
    "name": "job",
    "query": "label_values(memcached_up, job)"
   }
  ]
 },
 "panels": [
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (command) (rate (memcached_commands_total{cluster=\"$cluster\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Evicts & Reclaims",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate (memcached_items_evicted_total{cluster=\"$cluster\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "evicts"
    },
    {
     "expr": "sum (rate (memcached_items_reclaimed_total{cluster=\"$cluster\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "reclaims"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate (memcached_commands_total{cluster=\"$cluster\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_current_items{cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate (memcached_commands_total{status=\"hit\",command=\"get\",cluster=\"$cluster\",job=\"$job\"}[$__rate_interval]))\n/\nsum by (pod) (rate (memcached_commands_total{command=\"get\",cluster=\"$cluster\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (pod) (container:cpu_utilisation:ratio{cluster=\"$cluster\",workload=\"memcached-tenant-reconciler\"})",
     "legendFormat": "{{pod}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (pod) (memcached_current_bytes{cluster=\"$cluster\",job=\"$job\"})\n/\nsum by (pod) (memcached_limit_bytes{cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "{{pod}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_uptime_seconds{cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(memcached_read_bytes_total{cluster=\"$cluster\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(memcached_written_bytes_total{cluster=\"$cluster\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_current_connections{cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}